[package]
name = "crab"
version = "0.1.0"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
whoami = "1.1.1"
ctrlc = "3.1.8"
shared_child = "0.3.5"
crossterm = "0.19.0"
glob = "0.3.0"
dirs = "3.0.1"
nom = "6.1.2"
directories = "3.0.1"
unicode-segmentation = "1.7.1"

[workspace]
members = [
    "parser"
]
