[package]
name = "crust"
version = "0.1.0"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ansi-escapes = "0.1.1"
bigdecimal = "0.3.0"
bytecount = "0.6.2"
clap = "2.33.3"
crossterm = "0.20.0"
ctrlc = "3.2.0"
directories = "3.0.1"
dirs = "3.0.1"
glob = "0.3.0"
miette = { version = "3.3.0", features = ["fancy"] }
num-traits = "0.2.14"
phf = { version = "0.10.0", features = ["macros"] }
rand = "0.8.4"
rustyline = "9.0.0"
slab = "0.4.4"
subprocess = "0.2.8"
timing = "*"
whoami = "1.1.1"
yansi = "0.5.0"
thiserror = "1.0.30"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[target.'cfg(unix)'.dependencies]
nix = "0.22.1"
