[package]
name = "crust"
version = "0.1.0"
authors = ["Axel Kappel <axel.e.kappel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytecount = "0.6.2"
clap = "2.33.3"
colored = "2.0.0"
crossterm = "0.20.0"
directories = "3.0.1"
dirs = "3.0.1"
glob = "0.3.0"
rustyline = "8.2.0"
#ctrlc = "3.1.8"
shared_child = "0.3.5"
thin-string = "0.1.3"
thin-vec = "0.2.3"
timing = "*"
whoami = "1.1.1"
