#[derive(PartialEq, Debug)]
pub enum Token {
    Argument(String),
    Variable(String),
    Glob(String),
    String(String),
    Number(f64),
    NewLine,
    Space,
    Equality,
    Pipe,
    LessThen,
    GreaterThen,
    RightBrace,
    LeftBrace,
    RightParen,
    LeftParen,
    Colon,
    SemiColon,
    EOF,
}
