[package]
name = "parser"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallstr = "0.2.0"
bytecount = "0.6.2"
colored = "2.0.0"
